export interface AdjustableContent {
    class: string;
    title: string;
    paragraphs: string[];
}

export const PageContent: AdjustableContent[] = [
  { 'class': 'item-A', 'title': 'We are men of action, lies do not become us.', 'paragraphs': ['Isn\'t there any way you trust me? Nothing comes to mind. I swear on the soul of my father, Domingo Montoya, you will reach the top alive. Throw me the rope.', 'Can you move at all? Move? You\'re alive. If you want I can fly.', 'Roberts had grown so rich, he wanted to retire. He took me to his cabin and he told me his secret. \'I am not the Dread Pirate Roberts\' he said. \'My name is Ryan; I inherited the ship from the previous Dread Pirate Roberts, just as you will inherit it from me. The man I inherited it from is not the real Dread Pirate Roberts either. His name was Cummerbund. The real Roberts has been retired 15 years and living like a king in Patagonia.\''] },
  { 'class': 'item-B', 'title': 'I challenge you to a battle of wits.', 'paragraphs': ['You never said anything about killing anyone. I\'ve hired you to help me start a war. It\'s an prestigious line of work, with a long and glorious tradition. I just don\'t think it\'s right, killing an innocent girl. Am I going MAD, or did the word \'think\' escape your lips? You were not hired for your brains, you hippopotamic land mass. I agree with Fezzik. Oh, the sot has spoken. What happens to her is not truly your concern. I will kill her. And remember this, never forget this: when I found you, you were so slobbering drunk, you couldn\'t buy brandy! And YOU: friendless, brainless, helpless, hopeless! Do you want me to send you back to where you were? Unemployed, in Greenland?', 'Doesn\'t sound too bad. I\'ll try to stay awake. Oh, well, thank you very much, very nice of you. Your vote of confidence is overwhelming.', 'She is alive, or was an hour ago. If she is otherwise when I find her I shall be very put out.']},
  { 'class': 'item-C', 'title': 'Please consider me as an alternative to suicide.', 'paragraphs': ['Enough of that. Fezzik, are there rocks ahead? If there are, we all be dead.', 'Why do you wear a mask? Were you burned by acid, or something like that? Oh no, it\'s just that they\'re terribly comfortable. I think everyone will be wearing them in the future.', 'HE DIDN\'T FALL? INCONCEIVABLE. You keep using that word. I do not think it means what you think it means.']}
];